import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import axios from "axios";
import { PlayIcon } from "@heroicons/react/24/outline";

import { useAudio } from "../contexts/AudioContext";
import { Audio } from "../types";
import onAudioClick from "../utils/onAudioClick";
import getBaseURL from "../utils/getBaseURL";

const Home: NextPage = () => {
  const { audios, setPlayingNow } = useAudio();

  return (
    <div className="mx-auto my-auto flex items-center justify-center h-screen flex-col space-y-5">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full max-w-sm mb-10">
        <h2 className="text-3xl text-gray-600 font-semibold mb-3">Playlists</h2>

        <div className="space-y-4">
          {audios.map((audio) => (
            <button
              type="button"
              key={audio.slug}
              onClick={() =>
                onAudioClick(audio, () => setPlayingNow(audio.slug))
              }
              className="py-3 px-4 rounded-lg group w-full text-center even:bg-gray-100 odd:bg-transparent hover:bg-green-500 transition-all duration-150 flex items-center"
            >
              <PlayIcon className="w-5 h-5 text-gray-500 group-hover:text-white mr-3 transition-all duration-150" />
              <span className="text-gray-500 group-hover:text-white transition-all duration-150">
                {audio.title}
              </span>
            </button>
          ))}
        </div>
      </div>

      <Link passHref href="/novri">
        <a className="text-lg text-orange-500 font-medium">Go to other page</a>
      </Link>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  const audios: Array<Audio> = [
    {
      duration: 2 * 60,
      singer: "ILLENIUM",
      slug: "fortress",
      title: "Fortress by ILLENIUM",
      src: "/musics/fortress.mp3",
    },
    {
      duration: 2 * 60,
      singer: "Marsmello",
      slug: "singMeToSleep",
      title: "Sing Me to Sleep by Marsmello",
      src: "/musics/singMeToSleep.mp3",
    },
  ];

  const BASE_URL = getBaseURL();

  const {
    data: { data: playingNow },
  } = await axios.get(`${BASE_URL}/api/redis?key=playingNow`);

  return {
    props: {
      audios,
      playingNow,
    },
  };
}
